# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    continue-on-error: true
    - name: Check test coverage
      run: |
        test_result=$(npm run test --silent)
        coverage=$(echo "$test_result" | grep "Test Coverage:" | awk '{print $3}' | sed 's/%//')
        echo "Test Coverage: $coverage%"
        echo "::set-output name=coverage::$coverage"
    - name: Block PR on test failure or low coverage
      if: ${{ failure() && steps.check_test_coverage.outputs.coverage < 98 }}
      run: echo "Tests failed or coverage is below 98%. Please fix the issues before merging."
